### ISSUE TITLE
localhost link

### ISSUE THREAD

**Issue by ktfleming** [d12frosted/d12frosted.io#21]
Hi,

I was reading your "Task Management with org-roam" series (very helpful, by the way!) and noticed that in each article, in the series index (near the bottom of the page), the link to the first article "Path to Roam" is using a `localhost` link instead of a `d12frosted.io` link.

**Comment by d12frosted** [comment]
🤦 Fixed via 2d3dad8

Thanks for letting me know @ktfleming 💯
